// <auto-generated />
namespace Ado_Linq_NTT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTableGuest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableGuest));
        
        string IMigrationMetadata.Id
        {
            get { return "202201161800352_addTableGuest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
